name: Drug Interaction Checker
on:
  push:
    branches: [ main ] # hw project, so there are no branches
  pull_request:
    branches: [ main ]
  workflow_dispatch: # to manually trigger :D

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Docker stuff
      run: |
        docker-compose up -d --build
        sleep 15

    - name: Run tests
      run: |
        python -m pytest tests/
    
    - name: Cleanup
      run: |
        docker-compose down